package com.careplus.server.service;

import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.careplus.common.model.Payment;
import com.careplus.common.net.Request;
import com.careplus.common.net.Response;

/*
 * PaymentService
 * Saves payments and serves up a patient's payment history.
 *
 * This one and AuthService were the first two we got working, so every other
 * service copied their shape: start the session, do the work, roll back if it
 * goes wrong, always endSession in a finally.
 */
public class PaymentService extends BaseService {

	private static final Logger logger = LogManager.getLogger(PaymentService.class);

	public Response pay(Request request) {

		/*
		 * The Payment turns up already built by the client instead of us piecing it
		 * together from separate parameters. Keeps the request to one object and means
		 * the payment fields are only written out in one place.
		 */
		Payment payment = (Payment) request.getParams().get("payment");

		startSession();

		try {
			logger.info("Payment received: {}", payment);

			/*
			 * persist rather than merge, since the ID is generated by the database and
			 * this is always a brand new row. Hibernate hands out the ID here but the
			 * actual INSERT might not reach the database until endSession commits, so if
			 * a constraint is broken it blows up there and not on this line.
			 */
			session.persist(payment);

			resp.setSuccess(true);

			resp.setMessage("Payment added to database successfully");

		} catch (Exception e) {

			transaction.rollback();
			resp.setSuccess(false);
			resp.setMessage("Failed to save payment");

			logger.error("Could not save payment", e);

		}

		finally {

			endSession();
		}

		return resp;

	}

	public Response getPayments(Request request) {

		startSession();

		String id = (String) request.getParams().get("patientId");

		try {
			/*
			 * This is HQL, not SQL: "Payment" is the entity and "patientId" is the Java
			 * field, so it still works if the table or column names change.
			 *
			 * The ?1 placeholder with setParameter is what keeps this safe. If we glued
			 * the ID straight into the string instead, someone could type a crafted
			 * "patient ID" and read other people's records.
			 *
			 * Note there's no limit on this. A patient with a long billing history sends
			 * every single row back in one Response, across the socket and into a JTable.
			 * We'd need paging before this could handle real numbers.
			 */
			List<Payment> payments = session.createQuery("FROM Payment WHERE patientId = ?1", Payment.class)
					.setParameter(1, id).list();

			resp.setSuccess(true);
			resp.setMessage("Payments found");
			/*
			 * The list Hibernate gives back is Serializable so it goes over the wire fine.
			 * Anything lazily loaded inside these would blow up on the client with a
			 * LazyInitializationException though, because the session is already closed by
			 * the time we write the Response. Payment is only Strings and numbers, so
			 * there's nothing lazy in it to go wrong.
			 */
			resp.setData(payments);

		}

		catch (Exception e) {

			transaction.rollback();
			resp.setSuccess(false);
			resp.setMessage("Failed to get payment");

			logger.error("Could not load payments for patient {}", id, e);

		} finally {

			endSession();
		}

		return resp;
	}

}
