package com.careplus.client.patient.view;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

public class PaymentView extends JInternalFrame {

    private static final long serialVersionUID = 1L;

    // Labels
    private JLabel lblTitle;
    private JLabel lblPaymentId;
    private JLabel lblAmount;
    private JLabel lblMethod;
    private JLabel lblStatus;

    // Fields
    private JTextField txtPaymentId;
    private JTextField txtAmount;
    private JTextField txtMethod;
    private JTextField txtStatus;

    // Buttons
    private JButton btnPay;
    private JButton btnRefresh;
    private JButton btnClear;

    // Table
    private JTable tblPayments;
    private DefaultTableModel tableModel;

    public PaymentView() {

        super("Payments", true, true, true, true);

        initializeComponents();
        buildGUI();
        configureKeyboardShortcuts();

        setSize(900, 600);
        setVisible(true);

    }

    private void initializeComponents() {

        lblTitle = new JLabel("Payment Management");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 20));

        /*
         * The existing variable names are retained.
         * The displayed labels now match the Payment UML class.
         */
        lblPaymentId = new JLabel("Payment ID");
        lblAmount = new JLabel("Amount Paid");
        lblMethod = new JLabel("Outstanding Balance");
        lblStatus = new JLabel("Description");

        txtPaymentId = new JTextField(20);
        txtAmount = new JTextField(20);
        txtMethod = new JTextField(20);
        txtStatus = new JTextField(20);

        /*
         * Payment ID and outstanding balance are supplied
         * by the server and cannot be edited manually.
         */
        txtPaymentId.setEditable(false);
        txtMethod.setEditable(false);

        /*
         * Label mnemonics.
         */
        lblPaymentId.setDisplayedMnemonic(KeyEvent.VK_I);
        lblPaymentId.setLabelFor(txtPaymentId);

        lblAmount.setDisplayedMnemonic(KeyEvent.VK_A);
        lblAmount.setLabelFor(txtAmount);

        lblMethod.setDisplayedMnemonic(KeyEvent.VK_O);
        lblMethod.setLabelFor(txtMethod);

        lblStatus.setDisplayedMnemonic(KeyEvent.VK_D);
        lblStatus.setLabelFor(txtStatus);

        /*
         * Field tooltips.
         */
        txtPaymentId.setToolTipText(
                "The unique payment ID generated by the system.");

        txtAmount.setToolTipText(
                "Enter the amount being paid. Shortcut: Alt+A.");

        txtMethod.setToolTipText(
                "Displays the patient's outstanding balance.");

        txtStatus.setToolTipText(
                "Enter a short payment description. Shortcut: Alt+D.");

        btnPay = new JButton("Make Payment");
        btnRefresh = new JButton("Refresh");
        btnClear = new JButton("Clear");

        /*
         * Button mnemonics.
         */
        btnPay.setMnemonic(KeyEvent.VK_M);
        btnRefresh.setMnemonic(KeyEvent.VK_R);
        btnClear.setMnemonic(KeyEvent.VK_C);

        /*
         * Button tooltips.
         */
        btnPay.setToolTipText(
                "Submit the payment. Shortcut: Alt+M or Ctrl+Enter.");

        btnRefresh.setToolTipText(
                "Reload payment records. Shortcut: Alt+R or F5.");

        btnClear.setToolTipText(
                "Clear the payment fields. Shortcut: Alt+C or Escape.");

        tableModel = new DefaultTableModel();

        tableModel.setColumnIdentifiers(new Object[]{
                "Payment ID",
                "Amount Paid",
                "Outstanding Balance",
                "Description"
        });

        tblPayments = new JTable(tableModel);
        tblPayments.setRowHeight(25);
        tblPayments.setFillsViewportHeight(true);
        tblPayments.setAutoCreateRowSorter(true);
        tblPayments.setToolTipText(
                "Displays the patient's payment history.");

    }

    private void buildGUI() {

        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(
                BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JPanel formPanel = new JPanel(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();

        gbc.insets = new Insets(6, 6, 6, 6);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;

        formPanel.add(lblTitle, gbc);

        gbc.gridwidth = 1;

        gbc.gridx = 0;
        gbc.gridy = 1;
        formPanel.add(lblPaymentId, gbc);

        gbc.gridx = 1;
        formPanel.add(txtPaymentId, gbc);

        gbc.gridx = 0;
        gbc.gridy = 2;
        formPanel.add(lblAmount, gbc);

        gbc.gridx = 1;
        formPanel.add(txtAmount, gbc);

        gbc.gridx = 0;
        gbc.gridy = 3;
        formPanel.add(lblMethod, gbc);

        gbc.gridx = 1;
        formPanel.add(txtMethod, gbc);

        gbc.gridx = 0;
        gbc.gridy = 4;
        formPanel.add(lblStatus, gbc);

        gbc.gridx = 1;
        formPanel.add(txtStatus, gbc);

        JPanel buttonPanel = new JPanel(new FlowLayout());

        buttonPanel.add(btnPay);
        buttonPanel.add(btnRefresh);
        buttonPanel.add(btnClear);

        mainPanel.add(formPanel, BorderLayout.NORTH);
        mainPanel.add(new JScrollPane(tblPayments), BorderLayout.CENTER);
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);

        add(mainPanel);

    }

    private void configureKeyboardShortcuts() {

        /*
         * Ctrl + Enter makes a payment.
         */
        getRootPane().getInputMap(
                JComponent.WHEN_IN_FOCUSED_WINDOW
        ).put(
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_ENTER,
                        InputEvent.CTRL_DOWN_MASK
                ),
                "makePayment"
        );

        getRootPane().getActionMap().put(
                "makePayment",
                new AbstractAction() {

                    private static final long serialVersionUID = 1L;

                    @Override
                    public void actionPerformed(
                            java.awt.event.ActionEvent event) {

                        btnPay.doClick();
                    }
                }
        );

        /*
         * F5 refreshes the payment records.
         */
        getRootPane().getInputMap(
                JComponent.WHEN_IN_FOCUSED_WINDOW
        ).put(
                KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0),
                "refreshPayments"
        );

        getRootPane().getActionMap().put(
                "refreshPayments",
                new AbstractAction() {

                    private static final long serialVersionUID = 1L;

                    @Override
                    public void actionPerformed(
                            java.awt.event.ActionEvent event) {

                        btnRefresh.doClick();
                    }
                }
        );

        /*
         * Escape clears the payment fields.
         */
        getRootPane().getInputMap(
                JComponent.WHEN_IN_FOCUSED_WINDOW
        ).put(
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                "clearPaymentFields"
        );

        getRootPane().getActionMap().put(
                "clearPaymentFields",
                new AbstractAction() {

                    private static final long serialVersionUID = 1L;

                    @Override
                    public void actionPerformed(
                            java.awt.event.ActionEvent event) {

                        btnClear.doClick();
                    }
                }
        );

    }

    public void clearTable() {
        tableModel.setRowCount(0);
    }

    public void addPayment(Object[] row) {
        tableModel.addRow(row);
    }

    public void clearFields() {

        txtPaymentId.setText("");
        txtAmount.setText("");
        txtMethod.setText("");
        txtStatus.setText("");

        txtAmount.requestFocusInWindow();

    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public JTextField getTxtPaymentId() {
        return txtPaymentId;
    }

    public JTextField getTxtAmount() {
        return txtAmount;
    }

    public JTextField getTxtMethod() {
        return txtMethod;
    }

    public JTextField getTxtStatus() {
        return txtStatus;
    }

    public JTable getTblPayments() {
        return tblPayments;
    }

    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    public JButton getBtnPay() {
        return btnPay;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

}
