package com.careplus.common.net;

public enum RequestType {
    LOGIN_PATIENT,
    LOGIN_EMPLOYEE,
    GET_DOCTORS,
    GET_DEPARTMENTS,
    SCHEDULE_APPOINTMENT,
    UPDATE_APPOINTMENT,
    CANCEL_APPOINTMENT,
    GET_MY_APPOINTMENTS,
    SUBMIT_COMPLAINT,
    UPDATE_COMPLAINT,
    DELETE_COMPLAINT,
    GET_MY_COMPLAINTS,
    GET_MY_PAYMENTS,
    MAKE_PAYMENT,
    GET_MEDICAL_RECORDS,
    GET_ALL_COMPLAINTS,
    RESPOND_TO_COMPLAINT,
    ASSIGN_STAFF,
    GET_STAFF_ASSIGNMENTS,
    ADD_DIAGNOSIS,
    UPDATE_DIAGNOSIS,
    GET_DIAGNOSIS_RECORDS,
    RECORD_VITALS,
    CHAT_SEND,
    CHAT_POLL
}
